version: '3.7'

services:
  WebServer:
    image: "infomagazine_web_server:dev_v${VERSION}"
    build:
      context: .
      dockerfile: ./docker/dev/nginx/Dockerfile
    volumes:
      - tmp_data:/tmp

  APIServer:
    image: "infomagazine_api_service:dev_v${VERSION}"
    build:
      context: .
      dockerfile: ./docker/dev/web/Dockerfile
    volumes:
      - ./backend:/home/api
      - tmp_data:/tmp

volumes:
  tmp_data:
