version: '3.7'

services:
  WebServer:
    networks:
      - backend
    restart: on-failure
    ports:
      - '80:8080'
    depends_on:
      - APIServer

  APIServer:
    networks:
      - backend
    tty: true
    env_file:
      - api.base.env
networks:
  backend:
    driver: 'bridge'